[package]
name = "psi"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "psi"
path = "src/bin/main.rs"

[lib]
name = "psilib"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html




[dependencies]
