[package]
name = "psi"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "psi"
path = "src/bin/main.rs"

[lib]
name = "psi"
path = "src/lib.rs"



[dependencies]
dyn-clonable = "0.9.0"
eyre = "0.6.8"
lazy_static = "1.4.0"
uuid = { version = "1.1.2", features = ["v4", "fast-rng"] }
