[package]
name = "psi-proc-macro-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psi = { path = "../" }
psi-proc-macro = { path = "../psi-proc-macro" }
